// this file was generated by the xRM Test Framework VS Extension

#region Imports

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata.Query;
using Microsoft.Xrm.Sdk.Query;
using Yagasoft.Libraries.Common;

#endregion

namespace $rootnamespace$
{
	/// <summary>
	///     This plugin ... .<br />
	///     Version: 0.1.1
	/// </summary>
	public class $safeitemrootname$ : IPlugin
	{
		////public string UnsecureConfig { get; set; }

		////public $safeitemrootname$(string unsecureConfig, string secureConfig)
		////{
		////	UnsecureConfig = unsecureConfig;
		////}

		public void Execute(IServiceProvider serviceProvider)
		{
			////var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
			new $safeitemrootname$Logic().Execute(this, serviceProvider, PluginUser.ContextUser);
		}
	}

	internal class $safeitemrootname$Logic : PluginLogic<$safeitemrootname$>
	{
		////private string config { get; set; }

		public $safeitemrootname$Logic() : base("Create", PluginStage.PreOperation, "account")
		{
			////config = plugin.UnsecureConfig;
		}

		////protected override bool IsContextValid()
		////{
		////	

		////	return true;
		////}
		
		protected override void ExecuteLogic()
		{
			// get the triggering record
			////var target = (Entity)context.InputParameters["Target"];
			////var typedTarget = target.ToEntity<Entity>();

			////Yagasoft.Libraries.Common.CrmHelpers.LogAttributeValues(target.Attributes, target, log);

			// plugin logic ...

		}
	}
}
